### ISSUE TITLE
expand the error reporting

### ISSUE THREAD

**Issue by damianoneill** [rpinchbeck/Abnf-To-Antlr#6]
Hi @rpinchbeck was wondering if it's possible to expand the error output on http://www.robertpinchbeck.com/abnf_to_antlr/Default.aspx 

I tried the tool with a custom abnf grammar, getting a failure 'Unexpected node type encountered.'

Would be good if it identified the line at which the failure occurs or include some additional information. 

Thanks for the tool,
Damian.

p.s. I've attached the problem abnf if this helps.

[yang.abnf.zip](https://github.com/rpinchbeck/Abnf-To-Antlr/files/3321608/yang.abnf.zip)

**Comment by rpinchbeck** [comment]
Thanks, I will look into it.

**Comment by rpinchbeck** [comment]
In ABNF, whitespace at the beginning of a line indicates that the line is a continuation of the previous rule.  So, I removed all of the leading whitespace for rules using search and replace in Visual Studio Code with this regular expression... ```(^\s+)(?=[a-zA-Z][a-zA-Z0-9-]+\s*\=)```

Right now, Abnf-To-Antlr only supports RFC 5234 (ABNF), but literal text strings are part of RFC 7405 (ABNF).  So, I changed all %s"{string}" expressions to "{string}".

Here is the corrected ABNF grammar...
[yang-corrected.abnf.txt](https://github.com/rpinchbeck/Abnf-To-Antlr/files/3352853/yang-corrected.abnf.txt)

It appears that there is a bug in the indirect translation where it runs out of memory.  This is likely due to your grammar specifying a large number of characters, but I will need to look into it further.  A direct translation of the grammar works.

Here is the resulting ANTLR grammar...
[yang-direct-translation.antlr.g.txt](https://github.com/rpinchbeck/Abnf-To-Antlr/files/3352854/yang-direct-translation.antlr.g.txt)

**Comment by rpinchbeck** [comment]
Added support for case-sensitive strings per [RFC 7405](https://tools.ietf.org/html/rfc7405) and [Errata 5334](https://www.rfc-editor.org/errata/eid5334).

Also added error details including line and column.

**Comment by rpinchbeck** [comment]
Here is a corrected grammar that works with the latest version of Abnf-To-Antlr...
[corrected-yang-2020-01-05.txt](https://github.com/rpinchbeck/Abnf-To-Antlr/files/4022916/corrected-yang-2020-01-05.txt)

**Comment by damianoneill** [comment]
@rpinchbeck thankyou very much for this, much appreciated.  Happy new year to you.  

Damian.
